### ISSUE TITLE
Routing Errors for /admin/customer_returns & /admin/promotions on Commit 954d124

### ISSUE THREAD

**Issue by jovmilan95** [spree/spree_starter#1184]
After checking out commit 954d124 and running docker compose up, I encountered routing errors when accessing:
	•	/admin/customer_returns → uninitialized constant Spree::Admin::ReturnIndexController
	•	/admin/promotions → uninitialized constant Spree::Admin::PromotionsController

Docker Compose File Used:
```
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"

  spree:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres@postgres:5432/postgres
      RAILS_ENV: development
      SECRET_KEY_BASE: 'secret'
      RAILSDB: postgresql
      DB: postgres


volumes:
  postgres:
```

Steps to Reproduce:
	1.	Checkout commit 954d124
	2.	Run docker compose up --build
	3.	Visit /admin/customer_returns or /admin/promotions

Expected Behavior:

Admin pages should load without errors.

Actual Behavior:

Routing errors due to missing controllers.

Environment:
	•	Spree Starter Commit: 954d124
	•	Services: PostgreSQL latest, Spree app
	•	Rails Environment: development

Screenshots attached. Any ideas? 🚀

<img width="1439" alt="Image" src="https://github.com/user-attachments/assets/2d26c820-5218-4681-9101-a4b36695e2f7" />

<img width="1453" alt="Image" src="https://github.com/user-attachments/assets/189d7ef0-de4c-455a-b8f8-2bf318eed9a9" />
