### ISSUE TITLE
Service ports exposed by default, no indication that passwords on databases should be set

### ISSUE THREAD

**Issue by swelljoe** [spree/spree_starter#883]
The default config in docker-compose.yml has `ports:` defined for services like redis and postgresql, which, as I understand it, can expose them on a public IP. I noticed this because within a few minutes of spinning up a Spree starter instance, I saw weird permission denied errors from redis and found cryptominer malware running (apparently getting in through redis or postgres) under process name `kdevtmpfsi`. (see: https://github.com/docker-library/postgres/issues/798 and https://github.com/docker-library/postgres/issues/817 and https://github.com/docker-library/redis/issues/217 and https://github.com/docker-library/redis/issues/225 and so on...many such issues can be found).

The advice is always to not run the services openly, which seems reasonable. But, the Spree starter docker-compose has `ports` sections for most services that open these ports to the world, and no passwords are set and documentation does not suggest setting passwords for these services or indicate how it should be done.

e.g., from docker-compose.yml:

```yaml
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'
```

As far as I can tell, I don't think it's necessary to expose these services. The Docker network provides the necessary inter-container communication, I think? I don't understand it well enough to be sure, but I know that I can comment out the `ports` sections for redis and postgres and Spree seems to still work after a rebuild. I don't know if this is sufficient to prevent exploits, but I know the current Spree starter is wildly dangerous.
